apiVersion: v2
name: grommunio
description: A Helm chart for deploying grommunio groupware suite on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - grommunio
  - groupware
  - email
  - calendar
  - collaboration
home: https://grommunio.com
sources:
  - https://github.com/grommunio
maintainers:
  - name: Treibhaus
dependencies: []
